name: Daily Build JDTLS (JDK 21)

on:
  push:
  # schedule:
    # - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch jdtls
        run: |
          git clone --depth 1 https://github.com/eclipse-jdtls/eclipse.jdt.ls

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          cache-dependency-path: eclipse.jdt.ls/pom.xml

      - name: Build
        run: |
          cd eclipse.jdt.ls
          git apply ../1.patch
          ./mvnw clean verify -DskipTests

      - name: Locate Build Artifacts
        run: |
          cd eclipse.jdt.ls/org.eclipse.jdt.ls.product/target
          mv repository eclipse-jdt-ls 
          zip -r eclipse-jdt-ls-build.zip eclipse-jdt-ls

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jdtls-${{ github.run_id }}
          path: eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/*.zip
          retention-days: 3
